### ISSUE TITLE
Issue with st7036

### ISSUE THREAD

**Issue by wujku** [realPy/dothat-module#2]
Hello,
After executing
`insmod dothat.ko`
directory
`/sys/class/dothat/st7036`
is not exist. cap1166 and sn3218 works perfectly.

**Comment by realPy** [comment]
Hi :)
Have you enable SPI and I2C (with raspi-config)? 
Have you added the dtoverlay=nospidev in config.txt and add copy the nospidev.dtb in your /boot/overlays?

**Comment by wujku** [comment]
Yes, SPI and I2C enabled. 
/boot/config.txt has dtoverlay=nospidev parameter. 
nospidev.dtb is in /boot/overlays.
But after I enabled SPI in raspi-config shell output displays:
`modprobe: FATAL: Module spi-bcm2708 not found.`
I was using earlier python libraries for control dothat and display works properly.

Make command displays following errors:

> /home/pi/dothat-module/dothat-sn3218-sysfs.c: In function ‘store_sn3218_lcd_raw_callback’:
> /home/pi/dothat-module/dothat-sn3218-sysfs.c:140:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
>      struct psn3218 *pData=dev_get_drvdata(dev);
>      ^

Some info of my RPi:

`~ lsmod | grep spi`

> spi_bcm2835

`~ lsmod | grep i2c`

> i2c_bcm2708
> i2c_dev

**Comment by realPy** [comment]
Which kernel version ?
Uname -a

**Comment by wujku** [comment]
> Linux raspberrypi 4.4.6-v7+ #874 SMP Mon Apr 11 19:20:24 BST 2016 armv7l GNU/Linux

**Comment by realPy** [comment]
Ok same problem on last kernel.
spidev is mount and the nospidev.dtb doesn't work :/

**Comment by realPy** [comment]
Ok just rename nospidev.dtb by nospidev.dtbo..... in /boot/overlays it's crazy..

**Comment by wujku** [comment]
I pull last commit and run `sudo rpi-update`.

`uname -a`:
> Linux raspberrypi 4.4.7-v7+ #876 SMP Tue Apr 12 22:28:41 BST 2016 armv7l GNU/Linux

make command returns:

> make -C /lib/modules/4.4.7-v7+/build M=/home/pi/dothat-module modules
> make[1]: *** /lib/modules/4.4.7-v7+/build: No such file or directory.  Stop.
> Makefile:5: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by wujku** [comment]
It works, thanks!
